version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_forum
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: forum
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring_network

networks:
  spring_network:
    driver: bridge

volumes:
  mysql_data: